# Generated by Django 3.2.14 on 2022-07-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('ocupacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Abuelos',
        ),
        migrations.DeleteModel(
            name='Hermanos',
        ),
        migrations.DeleteModel(
            name='Padres',
        ),
    ]
